name = "tattletale-server"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "GAME_ROOM", class_name = "GameRoomDO" }
]

[[d1_databases]]
binding = "DB"
database_name = "tattletale"
database_id = "ab285525-99c1-4024-af2d-92226b2b94e3"
migrations_dir = "drizzle/migrations"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoomDO"]

[vars]
WEB_ORIGIN = "http://localhost:5173"
