export enum Phase {
  DAY_OPEN = 'DAY_OPEN',
  DAY_VOTE = 'DAY_VOTE',
  DAY_RESOLVE = 'DAY_RESOLVE',
  NIGHT_ACTIONS = 'NIGHT_ACTIONS',
  NIGHT_RESOLVE = 'NIGHT_RESOLVE',
  NIGHT_REVEAL = 'NIGHT_REVEAL',
}

export enum ChannelType {
  GLOBAL = 'GLOBAL',
  PRIVATE = 'PRIVATE',
  ROLE = 'ROLE',
  TEMP = 'TEMP',
  SYSTEM = 'SYSTEM',
  HACKER = 'HACKER',
}

export enum IntentType {
  SEND_MESSAGE = 'SEND_MESSAGE',
  SUBMIT_VOTE = 'SUBMIT_VOTE',
  SUBMIT_NIGHT_ACTION = 'SUBMIT_NIGHT_ACTION',
}

export enum NightActionType {
  HACKER_KILL = 'HACKER_KILL',
  PROTECT = 'PROTECT',
  INVESTIGATE = 'INVESTIGATE',
  MONITOR = 'MONITOR',
  JAM = 'JAM',
  MISDIRECT = 'MISDIRECT',
  IMITATE = 'IMITATE',
  CREATE_TEMP_CHAT = 'CREATE_TEMP_CHAT',
  CHANNEL_LOCK = 'CHANNEL_LOCK',
  SWAP_ROLE = 'SWAP_ROLE',
  VENGEFUL_KILL = 'VENGEFUL_KILL',
}

export enum SystemEventType {
  CHANNEL_LOCKED = 'CHANNEL_LOCKED',
  COMMUNICATION_JAMMED = 'COMMUNICATION_JAMMED',
  MESSAGE_INTEGRITY_COMPROMISED = 'MESSAGE_INTEGRITY_COMPROMISED',
  TEMP_CHANNEL_CREATED = 'TEMP_CHANNEL_CREATED',
  PSYCHIC_SIGNAL_RECEIVED = 'PSYCHIC_SIGNAL_RECEIVED',
  GAME_STARTED = 'GAME_STARTED',
  PLAYER_VOTED_OUT = 'PLAYER_VOTED_OUT',
  PLAYER_KILLED_AT_NIGHT = 'PLAYER_KILLED_AT_NIGHT',
  NO_KILL_TONIGHT = 'NO_KILL_TONIGHT',
  INVESTIGATION_RESULT = 'INVESTIGATION_RESULT',
  NIGHT_KILL_PROTECTED = 'NIGHT_KILL_PROTECTED',
}

export enum LobbyStatus {
  WAITING = 'WAITING',
  IN_GAME = 'IN_GAME',
  CLOSED = 'CLOSED',
}

export enum Team {
  FRIENDS = 'FRIENDS',
  HACKERS = 'HACKERS',
}

export enum SessionStatus {
  ACTIVE = 'ACTIVE',
  FRIENDS_WIN = 'FRIENDS_WIN',
  HACKERS_WIN = 'HACKERS_WIN',
}

export enum RoleId {
  // Friend team
  FRIEND = 'FRIEND',
  EXTROVERT = 'EXTROVERT',
  WHITE_HAT_HACKER = 'WHITE_HAT_HACKER',
  SECURITY_SPECIALIST = 'SECURITY_SPECIALIST',
  // Hacker team
  HACKER = 'HACKER',
  THE_BOSS = 'THE_BOSS',
  SIGNAL_JAMMER = 'SIGNAL_JAMMER',
  EAVESDROPPER = 'EAVESDROPPER',
  TROLLER = 'TROLLER',
  IMITATOR = 'IMITATOR',
}
